site_name: RaceResultExchange Documentation
site_author: 'Tobias Däuber'
docs_dir: docs/
repo_name: 'dbnetsoft/RaceResultExchangeDocumentation'
repo_url: 'https://github.com/dbnetsoft/RaceResultExchangeDocumentation'
nav:
    - Home: index.md
    - Setup: configuration/configuration.md
    - Scripting: 
        - General: scripting/index.md
        - Examples: scripting/examples.md
    - Photofinish:
        - Setup: photofinishsync/index.md
    - Displayboards: 
        - General: displayboards/index.md
        - Operation Modes: displayboards/modes.md
        - Scripting: displayboards/scripting.md
        - FDS MLED: 
            - General: displayboards/fdsmled/index.md
            - Scripting: displayboards/fdsmled/scripting.md
        - ALGE-Timing GAZ/DLine: 
            - General: displayboards/algegazdline/index.md
            - Scripting: displayboards/algegazdline/scripting.md
theme:
    name: material
    features:
        - navigation.tabs

markdown_extensions:
    - admonition
    - attr_list
    - def_list