site_name: RaceResultExchange Documentation
site_author: 'Tobias Däuber'
docs_dir: docs/
repo_name: 'dbnetsoft/RaceResultExchangeDocumentation'
repo_url: 'https://github.com/mhausenblas/actions-sandbox'
nav:
    - Home: index.md
    - Configuration: configuration.md
theme:
    name: bootstrap4