site_name: RaceResultExchange Documentation
site_author: 'Tobias Däuber'
docs_dir: docs/
repo_name: 'dbnetsoft/RaceResultExchangeDocumentation'
repo_url: 'https://github.com/dbnetsoft/RaceResultExchangeDocumentation'
nav:
    - Home: index.md
    - configuration/configuration.md
    - usage/usage.md
theme:
    name: material
